### ISSUE TITLE
Can not access http://c047-104-198-44-115.ngrok.io

### ISSUE THREAD

**Issue by LonelyAndFun42** [aashish2000/Parking_Management#1]
I try to test the repository on Google Colab.  After executing !python main.py. Try to access Public URL: http://c047-104-198-44-115.ngrok.io/.  The page show me ERR_NGROK_6022.

**Comment by aashish2000** [comment]
Hi @LonelyAndFun42, I've used NGROK for tunneling the localhost environment in Colab to a globally accessible URL. To create an NGROK tunnel you need to get an NGROk auth token from their website and add the command ngrok.set_auth_token() before ngrok.connect() in main.py

**Comment by LonelyAndFun42** [comment]
> Hi @LonelyAndFun42, I've used NGROK for tunneling the localhost environment in Colab to a globally accessible URL. To create an NGROK tunnel you need to get an NGROk auth token from their website and add the command ngrok.set_auth_token() before ngrok.connect() in main.py

Thank you very much. I have solved it according to your method.
